# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GameTitle', models.CharField(max_length=30, verbose_name='Title')),
                ('GameDescription', models.TextField(max_length=500, verbose_name='Description')),
                ('GameReleaseDate', models.DateField(default=django.utils.timezone.now, verbose_name='Release Date')),
                ('GamePlayerNumber', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('4+', '4+')], default='1', max_length=2, verbose_name='Players')),
                ('GamePhoto', models.ImageField(null=True, upload_to='', verbose_name='Image')),
                ('GameVideoURL', models.CharField(max_length=100, verbose_name='Video URL')),
                ('GameReview', models.TextField(max_length=500, verbose_name='Review')),
                ('GameRating', models.CharField(choices=[('1', '1'), ('1.5', '1.5'), ('2', '2'), ('2.5', '2.5'), ('3', '3'), ('3.5', '3.5'), ('4', '4'), ('4.5', '4.5'), ('5', '5')], default='1', max_length=3, verbose_name='Rating')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GenreTitle', models.CharField(max_length=30, verbose_name='Title')),
                ('GenreDescription', models.TextField(max_length=500, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlatformName', models.CharField(max_length=30, verbose_name='Title')),
                ('PlatformDescription', models.TextField(max_length=500, verbose_name='Description')),
                ('PlatformImage', models.ImageField(null=True, upload_to='', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PublisherName', models.CharField(max_length=30, verbose_name='Name')),
                ('PublisherCEO', models.CharField(max_length=30, verbose_name='CEO')),
                ('PublisherFoundDate', models.DateField(default=django.utils.timezone.now, verbose_name='Founded')),
                ('PublisherEmployeeNumber', models.IntegerField(verbose_name='Number of employees')),
                ('PublisherWebsite', models.CharField(max_length=30, verbose_name='Website')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='GameGenre',
            field=models.ManyToManyField(to='GamesDB.Genre', verbose_name='Genre'),
        ),
        migrations.AddField(
            model_name='game',
            name='GamePlatform',
            field=models.ManyToManyField(to='GamesDB.Platform', verbose_name='Platform'),
        ),
        migrations.AddField(
            model_name='game',
            name='GamePublisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GamesDB.Publisher', verbose_name='Publisher'),
        ),
    ]
