# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamesDB', '0002_game_gameismultiplayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='GameIsMultiplayer',
            field=models.BooleanField(verbose_name='Multiplayer'),
        ),
    ]
