# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamesDB', '0003_auto_20161212_0257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='GameIsMultiplayer',
        ),
        migrations.AddField(
            model_name='game',
            name='GameIsOnline',
            field=models.BooleanField(default=1, verbose_name='Online'),
            preserve_default=False,
        ),
    ]
