# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 01:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GamesDB', '0004_auto_20161212_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='GameIsOnline',
        ),
    ]
