# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamesDB', '0011_auto_20161217_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='GameReview',
            field=models.TextField(max_length=99999, verbose_name='Review'),
        ),
    ]
