# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 05:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GamesDB', '0013_auto_20161218_0656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='GamePlayerNumber',
        ),
    ]
