# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamesDB', '0014_remove_game_gameplayernumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='GameTitle',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
    ]
