# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamesDB', '0015_auto_20161218_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='PublisherSlug',
            field=models.CharField(default=1, max_length=30, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
