# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GamesDB', '0016_publisher_publisherslug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='PublisherSlug',
        ),
    ]
