# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-06 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamesDB', '0017_remove_publisher_publisherslug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('GameTitle',)},
        ),
        migrations.AddField(
            model_name='game',
            name='GamePrice',
            field=models.FloatField(default=0, verbose_name='Price'),
            preserve_default=False,
        ),
    ]
